export const FETCH_DATA_START = 'FETCH_DATA_START'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'

export const ADD_ITEM_START = 'ADD_ITEM_START'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL'

export const REMOVE_ITEM_START = 'REMOVE_ITEM_START'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL'

export const EDIT_ITEM_START = 'EDIT_ITEM_START'
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS'
export const EDIT_ITEM_FAIL = 'EDIT_ITEM_FAIL'
export const SWITCH_TO_EDIT = 'SWITCH_TO_EDIT'


export const CHANGE_PROCESS = 'CHANGE_PROCESS'